### ISSUE TITLE
802.1x option not available while creating a new network

### ISSUE THREAD

**Issue by Molkenbur** [cucumber-tony/cucumber-frontend#113]
In edit mode of a network the option 802.1x is selectable, but not in creation mode.

See screenshot:
![image](https://cloud.githubusercontent.com/assets/14114203/16353651/d7152f3a-3a7d-11e6-94ac-0e707ad50f87.png)

**Comment by simonmorley** [comment]
Correct, this is very much intended. The aim of the create ssid screen is to define a network as quickly and simply as possible.

Since only a small percentage use 802.1x, we have omitted completely. As you mention, it's only available after you have created the ssid.

If required, you can use the API to create one.

**Comment by Molkenbur** [comment]
From my point of view this wizard thing confuses more than it helps. It seems to make it easier. But the user has two different edit pages and might mix them or is looking for one he could not reach any more.

**Comment by simonmorley** [comment]
Depending on how it's likely to impact the creation, we could possibly add some advanced options to the dialog.

**Comment by simonmorley** [comment]
Closing this. For now, we're sticking with the quick-creation model and don't want to pollute the simplicity with additional options that most don't use.

We will add a message about advanced options later - 802.1x is particularly tricky since it requires more setup than most + testing.

It's still possible to create all this in a single go with the API so, for adjustments like this, we would recommend modifying the page in another repo.
