### ISSUE TITLE
Internet Explorer 11 CORS

### ISSUE THREAD

**Issue by simonmorley** [cucumber-tony/cucumber-frontend#196]
That's all really, there's seemingly a problem with IE 11 and 10 that throws the following:

```
xmlhttprequest network error access is denied
```

I can't find anyway to fix this which means 11 is completely unusable. Edge is OK.

**Comment by simonmorley** [comment]
Actually this DOES affect Edge...

**Comment by Oceanspeed** [comment]
Possibly Firefox. Happy to test.

**Comment by simonmorley** [comment]
No, it doesn't affect firefox.

**Comment by ChristianWinkler** [comment]
you can't save changes to splashpages and devices settings currently in IE. Might this be an effect of this issue ?

**Comment by simonmorley** [comment]
Closing. Already open. Search for cors

**Comment by simonmorley** [comment]
@ChristianWinkler No - that's related to the CORS issue already open

**Comment by ChristianWinkler** [comment]
why is this closed ? is this a fix later ? i cant see any change 
![image](https://cloud.githubusercontent.com/assets/19971953/19681926/97ba44cc-9aab-11e6-8548-892f03ebca1e.png)

**Comment by simonmorley** [comment]
This was working for all other IE users. 

What version do you have :(

**Comment by mbecks** [comment]
We still see this issue on IE11 (Win 7 and 10).

The problem is the length of the URL sent with the PATCH request when changing something on the page. IE has a more conservative limit than other browsers and that limit is easily reached on that page. My suggestion is to send the data as payload instead of query params.

This issue might not be isolated to the splash page settings. I've seen that other pages send their PATCH data as queries as well. Depending on the size of the data you never known where the URL limit might be reached. So I would propose a more general solution that changes all PATCH requests across CT to use payload for data.

**Comment by simonmorley** [comment]
@mbecks Could you fork the repo and commit a single change so we can have a look.

**Comment by mbecks** [comment]
This has just the change for the splash settings. I recommend to make similar changes on all pages:

https://github.com/mbecks/cucumber-frontend/tree/patch-with-payload
