### ISSUE TITLE
Zones: When a network gets deleted, the Zones table doesn't get updated.

### ISSUE THREAD

**Issue by ChristianWinkler** [cucumber-tony/cucumber-frontend#288]
the counter for networks in the zones table on zones page does not recognize when a selected network gets gemoved from ct. (its counting well if the network gets unselected first)

**Comment by AndrewMargarit** [comment]
Confirmed.
**Actual Behavior**:
 -  `What is the issue? *` - Zones table doesn't reindex te number of Networks when a network gets deleted
 -  `What is the expected behaviour?` When you delete a network that's part of a zone, the number of Networks from the Zones tables should reflect the updated value.

**Additional Information**:
 -  `Browser Type: *` Chrome
 -  `Browser Version: *` 52
 -  `OS: *` Ubuntu 16.04
 -  `Page URL: *` /locations/name/zones

**Comment by simonmorley** [comment]
Agreed. Can we stick with the template we've created for a faster resolution.  Prevents yoyoing questions back and forth.

**Comment by simonmorley** [comment]
This is fixed on backend, changes should be live later. Will close in 24 hours if no further comments.
