### ISSUE TITLE
Client : "Connected To" Column Should Show AP name?

### ISSUE THREAD

**Issue by wifinigel** [cucumber-tony/cucumber-frontend#33]
In the client listing page, I think it would be more useful to show the AP name that a client is associated to in the "Connected To" column and have an additional "SSID" column for the SSID the client is using.

Screen shot below:

![connected to column](https://cloud.githubusercontent.com/assets/19818404/15901522/7a9c1f5a-2d9b-11e6-8072-b7137193c441.png)

**Comment by simonmorley** [comment]
Yeah, we have this in #14 but this is better.

**Comment by wifinigel** [comment]
I didn't realize that the option to select the AP name in the list of fields is already there as a selection option - I just found it. I think this looks OK as-is. It's just a change the Connected To field header to SSID. Sorry!

![issue-33-update](https://cloud.githubusercontent.com/assets/19818404/15923073/093d9e5a-2e23-11e6-988d-8e345844bd45.png)

**Comment by simonmorley** [comment]
Fixed a few things here:

- AP Description now links to the device. Previously, the URL was incorrect due to a missing parameter.
- Changed column name from Connected To ---> SSID as requested.
- Temporarily removed the txbps as it's showing as zero

Opening another issue for the txbps here: https://github.com/cucumber-tony/cucumber-frontend/issues/46
