### ISSUE TITLE
Client Signal Data Shows Erratic Levels Over Short Duration Intervals

### ISSUE THREAD

**Issue by wifinigel** [cucumber-tony/cucumber-frontend#458]
It's hard to solve a problem when important details are missing. For fast resolution of problems, include as much detail in the fields below.

**Actual Behavior**:
 -  `What is the issue? *` When looking at the signal level detail for an individual client, when a short duration interval is chosen for the span of the graph (i.e. 5mins, 30 mins, 60 mins), signal levels appear erratic for intervals when no data is available. It would be more useful to have gaps in data or plot between two data points rather than plotting values of zero. This data is viewed by expanding the signal strength panel from a client summary page.
 -  `What is the expected behavior?` A graph showing data gaps or average values to fill data gaps

**Additional Information**:
 -  `Browser Type: *` Chrome
 -  `Browser Version: *`Version 55.0.2883.87 m
 -  `OS: *`Windows 10
 -  `Page URL: *`https://my.ctapp.io/#/locations/home-lyndhurst-grove-jpiqs9iuj_ptuwohpovuda/clients/565d683b6cc3e3a634cdd862?period=30m

![image](https://cloud.githubusercontent.com/assets/19818404/21526065/73bc4458-cd19-11e6-9e27-0bd2ec5d5228.png)

----

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

> Add screenshots, gifs, illustrations as required to demonstrate your issue.

> No duplicates, please use the search tool.

**Comment by simonmorley** [comment]
I don't think it's realistic to plot averages rather than zero values. Wouldn't that would give the impression we have data to fill in the gaps?

**Comment by wifinigel** [comment]
I'd rather see gaps I guess.

**Comment by Molkenbur** [comment]
I noticed the same problem and it becomes rather worse, if you look at the 5min graph (see screenshot).
![image](https://cloud.githubusercontent.com/assets/14114203/21649374/cd7695a6-d2a1-11e6-8702-3409f12ea71b.png)

The devices send statistical data once a  minute. The 5min graph is drawn with values every 10 seconds. Thus the 5 values between the minute values are all zero.

The 30min interval graph is drawn with values every minute. If statistics from a device arrives later, then even the 30min graph has zero values.

Showing gaps instead of zero values would be acceptable for the 30min graph. An average value would distort the results. At least for the 5min graph another solution, like connecting all not zero values, could be better, because here we know, that zero and average values would be wrong.
