### ISSUE TITLE
Triggers : Number of issues with triggers

### ISSUE THREAD

**Issue by wifinigel** [cucumber-tony/cucumber-frontend#49]
Whist testing triggers for basic box up/box down alerts, found a number of issues with dynamic variables:

1. The variable {{ First_Name }} suggested in the built-in example does not seem to substitute (blank seen in email where value should be) 
2. The variable {{ Username }} shown in the common tags does not seem to substitute (blank seen in email where value should be) 
3. When firing a test trigger, where the tag substitution would occur, just see the word 'meta' in the trigger message text. For example, {{ Description }} is shown as the word meta. Although no real value can be substituted (as it is a test trigger), might be better to show a pseudo value for each tag, e.g. \<box description\> for {{ Description }}.
4. Carriage returns in a trigger definition in the body of an email are not reflected in the email sent.

Here is a screen shot of a trigger, email body definition & resulting email

![box-down-trigger-definition](https://cloud.githubusercontent.com/assets/19818404/15991976/41adf94a-30b9-11e6-8be4-d31c799b45f8.JPG)

![box-down-trigger-definition-email-body](https://cloud.githubusercontent.com/assets/19818404/15991978/46ed2eb2-30b9-11e6-8376-88af46b5d933.JPG)

![box-down-trigger-email]
(https://cloud.githubusercontent.com/assets/19818404/15991980/4c3221de-30b9-11e6-93fe-89554472cf94.JPG)

**Comment by simonmorley** [comment]
Could you put the screenshot of the other trigger in too please.

**Comment by wifinigel** [comment]
Oops, sorry, yes posted wrong one. Here is the one that corresponds to the email shown:

![image](https://cloud.githubusercontent.com/assets/19818404/16034642/c824ed06-320a-11e6-90db-301f1ef601ac.png)

**Comment by simonmorley** [comment]
https://github.com/cucumber-tony/cucumber-frontend/issues/85

**Comment by simonmorley** [comment]
**The variable {{ First_Name }} suggested in the built-in example does not seem to substitute (blank seen in email where value should be)**

The first and last name attributes are only available for events triggered by a social login. Made clear in dialog.

**The variable {{ Username }} shown in the common tags does not seem to substitute (blank seen in email where value should be)**

The username field only applies to guests - it is not _your_ username. Made clear in dialog.

I have removed these from the common tags now - they were in the wrong place. I have also removed the first_name tag from the default template as this was also mis-leading.

Just added the {{ Last_Heartbeat }}, {{ Public_Ip }} and {{ Wan_Ip }} tags to the boxes list.

Since these specific triggers are going directly to you, I can't see the need for a dynamic {{ username }} field. We have some changes coming to the triggers in the next version however, I'd prefer to keep these private for the time being ;)

The line breaks are now fixed for emails, at least.

I have replaced the word 'meta' with something 'better'. Will think about adding dynamic vars however, the test is really to prove deliverability, rather than context injection.

The changes will be live this afternoon!

Thanks @wifinigel for the thorough issue report :)

**Comment by wifinigel** [comment]
No probs!

{{Username}} does seem to substitute to the GUI user in the Slack triggers I've played with:

![image](https://cloud.githubusercontent.com/assets/19818404/16267471/c768964c-3881-11e6-9994-dd97b932235f.png)

![image](https://cloud.githubusercontent.com/assets/19818404/16267484/d9953294-3881-11e6-94dc-cc63c5e88bfa.png)

**Comment by simonmorley** [comment]
Ah, ok. I don't think I explained that well. And forgot an important part.

If something happens to a box, like a reboot, which is actioned by a user. The user who performed it will appear.  However, if a box goes offline (for example), the action isn't performed by anyone.... So, no name would appear.

Resync, reboot, reset etc. Should have a username.


Nice emojis btw!

**Comment by wifinigel** [comment]
OK, yes that makes sense. :)

On 22 June 2016 at 19:23, Simon (Big Chief) Morley <notifications@github.com
