### ISSUE TITLE
Enhancement Request - Accessing Reports

### ISSUE THREAD

**Issue by wifinigel** [cucumber-tony/cucumber-frontend#75]
As reports are location-specific, would it make more sense to access reports from within the location side-bar, rather than (or in addition to) the top-level drop-down?

It would be useful to perhaps access them as an additional link below the current "Triggers" link? (suggested screenshot below).

![image](https://cloud.githubusercontent.com/assets/19818404/16114516/95cd32a4-33b9-11e6-997d-667fc4168adb.png)

**Comment by simonmorley** [comment]
No, the reports are in a single place by design.

We're working on the filtering so you can filter whatever you need out.

They need to be in a single place otherwise we're maintaining two sets of the same thing. 

You'll be able to filter with much more soon.

See this issue: 

https://github.com/cucumber-tony/cucumber-frontend/issues/26
